server:
  port: 8080
  # 可选值: debug, test, production
  mode: test
  # 是否强制初始化权限（设为true会覆盖数据库中的权限设置）
  init_permissions: true

database:
  driver: mysql
  host: 8.218.231.227
  port: 3306
  username: gorse
  password: gorse_pass
  dbname: campus
  charset: utf8mb4
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600 # 连接最大生命周期(秒)

jwt:
  secret: your_jwt_secret_key
  expiration: 24 # in hours

upload:
  save_path: ./uploads
  allowed_types: jpg,jpeg,png,gif
  max_size: 5 # in MB

# RabbitMQ配置
rabbitmq:
  url: amqp://guest:HZMhzm@030614@8.218.231.227:5672/ # 可以直接用URL，或者用下面的参数构建URL
  host: localhost # 如果未提供URL，使用host、port、username和password
  port: 5672
  username: guest
  password: guest